### ISSUE TITLE
Spelling problems - Release notes

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#245]
About 30 lines down   title  Serach tag selection--> Search

two more para  down   Extended Secyruty question foils--> Security

next para   Checkbox toggle for Searche fields--> Search

all minor I know but the release notes keep getting updated without a change in these spelling errors.

Thanks

NK

**Comment by sbillard** [comment]
Many thanks. 

I've reviewed the document and found a few more spelling errors. But please point out any you should see. Sometimes it is difficult for me to see because I pattern match when reading due to mild dyslexia. So if something is close it will register as the correct word.

Maybe things will be better now, though. One of the new features is the ability to use nanoSpell with tinyMCE.
