### ISSUE TITLE
Strange behavior while manual sorting subalbums

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#316]
There is a strange behavior while manual sorting subalbums. Subalbums cant hold their position after mouse drag and drop and save. When I move first album to last position, after save it is in the middle, when I move it from middle to second position and save, it is in second position.

No order in this behavior...

I think subalbum sorting in album page doesnt work too - or behavior is strange.
All my albums with subalbums have chaotic sorting now.

ZenPhoto20 1.1.3.0

**Comment by sbillard** [comment]
I have not been able to reproduce this.  How many sub albums were on the page? Have you checked error logs to see if any error is being thrown? Is this true of all sub albums?

One possible thought is that there is an error in the database to start with. Can you do a "refresh database" and see if it changes anything?

**Comment by Mates-K1** [comment]
Refreshing database didnt help. Error log is clear.

After testing I thing problem is with albums which have more then 10 (or 9) subalbums (I havent got exactly 10 subalbums in gallery). In my primary album there is eight albums - so it is OK.

Lets see video - https://copy.com/VdZnptfeJeyJedEe
Follow the position of album "xxxxxxxxxxxxx 19. - 20. 12. 2014" - I put it on 3rd place, but after safe it is on 5th place...

**Comment by sbillard** [comment]
I am able to create fault moving albums. Not sure it is what you are seeing (I don't understand it yet.) If you could enable the "debug" plugin (development tab) and on the main admin page use the "mark release" button to set the site in debug mode then recreate the problem. If you get an invalid album instantiation your issue is probably what I have found.

**Comment by Mates-K1** [comment]
I tried recreate problem in debug mode. Nothing special happend - I got same strange albums moving.

There is a log - without users info (about 8000 rows :) ), I hope it helps.
https://copy.com/s9ybUzX0D8hTW9pV

**Comment by sbillard** [comment]
You should go to the options page and un-check the check boxes for the mark release feature. These items are not necessary (for this issue) and make the log impossible to really examine. But anyway, I did not see anything that seemed related. The problem I have encountered is with dynamic albums. I need to fix it and then continue to see if I can reproduce your problem.

**Comment by sbillard** [comment]
I have fixed the issue I encountered in the 1.1.3.3 build. Please try it incase it also fixes your issue. With this fix in place I have not been able to reproduce a sorting failure. I have tried albums with 5, 9, and 18 sub-albums and all work for me.

If you still have the problem we will have to make some special debugging patches to try to understand what is going on.

**Comment by Mates-K1** [comment]
So... 1.1.3.3. didnt help. :(

But there is order in this chaos. Testing with 11, 12 and 36 subalbums.

For 36 subalbums (moving sublabum from position 25 to 26):
1 and 2 - first 2 subalbums are ALWAYS OK
11 - 20,
3,
26,
25
27-30
4
31-36
5-10

For 12 subalbums (moving one album of 4 - 9):
1 and 2 (still OK)
11 - 12 (moving next 10 albums - if exists)
3
moved album
another albums with original order

Rules:
- first 2 albums are OK,
- follow albums from 11 - 20,
- follow album 3,
- follow album 21 - 30,
- follow album 4,
- follow album 31 - 40,...
- follow unused albums from first 10.

(not 100% - there are some exceptions or another rules)

So... I am a little bit confused of this behavior. :)
Sorting by name, date etc. seems ok.

**Comment by sbillard** [comment]
I admit I am not sure of your description, but I have created an album with subalbums A (1)...A (12). I have not seen a move sequence that fails. So maybe you can describe a script that fails, for instance:

Albums in 1-12 order.
Move album A (1) to after album A (9)
Apply-albums in expected order
Move album A (4) to after album A (8) 
Apply--now album A (7) is after album A (12) which would be wrong.

Anyway with such a script I will either be able to reproduce your situation or not. If not at least we will have a control situation so that we can try to log on what happens on your site and I can compare it to what happens on my site.

**Comment by Mates-K1** [comment]
I think - simplest solution will be if you login to my gallery. I will send you login info for this case. What is your mail please?

**Comment by sbillard** [comment]
email: stephen@sbillard.org

**Comment by Mates-K1** [comment]
It is simple... choose some album with subalbums and try change manual subalbum order. For example "1. oddíl skautek" --> "Tábory" - 24 subalbums.

**Comment by sbillard** [comment]
Well, I can certainly see it happening on your site. Moving almost any album to the bottom leaves it in second place. As best as I can tell, this does not happen with containing less than 10 subalbums. It also does not happen on my site. I will think on this and figure out some debugging code to help figure this out.

**Comment by sbillard** [comment]
I have created a debug build at https://github.com/sbillard/ZenPhoto20-DEV/tree/subalbum_sort

Please load this build and let me know when it is there. It will produce debug information in the log for sorts that will, I hope, tell us what is happening.

**Comment by Mates-K1** [comment]
Uploaded... :)

**Comment by sbillard** [comment]
I think I know what the issue is. I think that for some reason your site is sorting integers differently than mine. so in that world the sort order is 0, 1, 10, 2.... Anyway, the fix should be to make the field a character field. That change is in the subalbum_sort branch, same link as above. Let me know if it works. If not we will try again. At least I know that the proposed order from the sort is correct and the problem is the sorting for displaying the albums.

**Comment by Mates-K1** [comment]
YES!!! Works perfectly!
Now I can sort subalbums manually again...
Thank you very much for your help in solving the problem.

**Comment by sbillard** [comment]
I should thank you. Without access to your site I would never have been able to figure out what was wrong.
