### ISSUE TITLE
Working on Ldap Plugin

### ISSUE THREAD

**Issue by gevatter** [ZenPhoto20/ZenPhoto20#352]
So we will write here until I push my first tries to my repo i think. (Btw: sry for my quirky english, im not a native speaker)

As far as I understand things, the federated logon meanisms a ment to push the browser somewhere else, do the authentiaction there and redirect to zenphoto. Am I getting this right?

So this is what we woult not need, as zenphoto needs to query the ldap server with the username and password and process the answer.

**Comment by sbillard** [comment]
You are correct on how the federated login works. But I am not sure how that is much different than querying the ldap server. Is that something that can be done "inline" or is it really a request/response mechanism? If the process can be handled in-line on the server then we can incorporate it into a version of the authentication library.

**Comment by gevatter** [comment]
It is the way your describe as inline. The ldap server is often installed on the same host as the webserver is running or at least in the same local network.
I've seen two ways of implementations, the one way is that for every request which happens in a program the ldap server is queried if the user has the required rights.
The other would be to check the ldap server at login, and if allowed create a local user which gets his rights from users and permissions settings.
Im not shure which screnario fits best here.

**Comment by sbillard** [comment]
The best way would be to check the LDAP server at login. If you can store ZenPhoto20 rights with the LDAP user. It is also possible to have a "mirror" user in the ZenPhoto20 user table. Then we would match the authenticated LDAP user to that table and  use the information stored there for permissions, etc. This latter works best if the two users are "independent" but does require managing the user in two places. Federated login works this way since there is no way of passing ZenPhoto20 rights back to the authorizing authority.

**Comment by sbillard** [comment]
ZenPhoto20 version 1.1.9.2 has been modified to help in this LDAP project.

PHP has a module for LDAP that can be configured. Presuming that you have configured that module the approach would be to create a new authorization class script named class-auth.php. The content of this file would be something like the following. NOTE, this has not been tested nor even syntax or feature checked. It is a starting point.

Assumptions:
1. You will be using the standard ZenPhoto20 login forms.
2. You can determin the rights of a user from information from the LDAP server
3. The LDAP server can either store or provide a unique integer for each user that can be used as an ID in database references.


/** class-auth.php**/

$host = 'myldap';
$domain = 'mydomain.ex';
$basedn = 'dc=mydomain,dc=ex';

require_once(dirname(__FILE__) . '/lib-auth.php');

class Zenphoto_Authority extends _Authority {
	function handleLogon() {
		global $_zp_current_admin_obj, $_zp_loggedin;
		$user = sanitize(@$_POST['user'], 0);
		$password = sanitize(@$_POST['pass'], 0);
		$_zp_loggedin = false;
		
		/** the following code is extracted from one of the PHP examples **/
		$ad = ldap_connect("ldap://{$host}.{$domain}") or die('Could not connect to LDAP server.');
		ldap_set_option($ad, LDAP_OPT_PROTOCOL_VERSION, 3);
		ldap_set_option($ad, LDAP_OPT_REFERRALS, 0);
		@ldap_bind($ad, "{$user}@{$domain}", $password) or die('Could not bind to AD.');
		$userdn = getDN($ad, $user, $basedn);
		if (checkGroupEx($ad, $userdn, getDN($ad, 'ZenPhoto20', $basedn))) {
				echo "You're authorized as ".getCN($userdn);
				
				/* find the following from the LDAP entry *?
				$id			// a unique integer that must not match the record ID of any local ZenPhoto20 administrator
				$name		//optional display name of the user
				$rights	//the ZenPhoto20 user rights to be assigned the user
				$email	//optional user e-mail address
				
				/** ZenPhoto20 code **/
				$_zp_current_admin_obj = Zenphoto_Authority::newAdministrator('');
				$_zp_current_admin_obj->transient = true;
				$_zp_current_admin_obj->setUser($user);
				$_zp_current_admin_obj->setName($name);
				$_zp_loggedin = $_zp_current_admin_obj->setRights($rights);
				$_zp_current_admin_obj->setEmail($email);
				$_zp_current_admin_obj->setID($id);
				//set any other significant fields you might want to use later, for instance locale, group() for a group, etc.
				
				/** end ZenPhoto20 code
		} else {
				echo 'Authorization failed';
		}
		ldap_unbind($ad);

	//if the logon failed you might want to revert to the standard logon, e.g. for a master administrator
	if !$_zp_loggedin) {
		$_zp_loggedin = parent::handleLogon();
	}
	return $_zp_loggedin;
}

class Zenphoto_Administrator extends _Administrator {
	function setID($id) {
		$this->set('id', $id);
	}
}

/** the following code is extracted from one of the PHP examples **/

/*
* This function searchs in LDAP tree ($ad -LDAP link identifier)
* entry specified by samaccountname and returns its DN or epmty
* string on failure.
*/
function getDN($ad, $samaccountname, $basedn) {
		$attributes = array('dn');
		$result = ldap_search($ad, $basedn,
				"(samaccountname={$samaccountname})", $attributes);
		if ($result === FALSE) { return ''; }
		$entries = ldap_get_entries($ad, $result);
		if ($entries['count']>0) { return $entries[0]['dn']; }
		else { return ''; };
}	
		
/*
* This function retrieves and returns CN from given DN
*/
function getCN($dn) {
    preg_match('/[^,]*/', $dn, $matchs, PREG_OFFSET_CAPTURE, 3);
    return $matchs[0][0];
}
		
/*
* This function checks group membership of the user, searching only
* in specified group (not recursively).
*/
function checkGroup($ad, $userdn, $groupdn) {
    $attributes = array('members');
    $result = ldap_read($ad, $userdn, "(memberof={$groupdn})", $attributes);
    if ($result === FALSE) { return FALSE; };
    $entries = ldap_get_entries($ad, $result);
    return ($entries['count'] > 0);
}

/*
* This function checks group membership of the user, searching
* in specified group and groups which is its members (recursively).
*/
function checkGroupEx($ad, $userdn, $groupdn) {
    $attributes = array('memberof');
    $result = ldap_read($ad, $userdn, '(objectclass=*)', $attributes);
    if ($result === FALSE) { return FALSE; };
    $entries = ldap_get_entries($ad, $result);
    if ($entries['count'] <= 0) { return FALSE; };
    if (empty($entries[0]['memberof'])) { return FALSE; } else {
        for ($i = 0; $i < $entries[0]['memberof']['count']; $i++) {
            if ($entries[0]['memberof'][$i] == $groupdn) { return TRUE; }
            elseif (checkGroupEx($ad, $entries[0]['memberof'][$i], $groupdn)) { return TRUE; };
        };
    };
    return FALSE;
}

**Comment by ariep** [comment]
Hi sbillard,

I'm trying to adapt the above concept to my situation (an OpenLDAP server with posix style users and groups), but I'm hitting a snag; maybe you can help.

I think I have the LDAP part covered: the binding to the server and querying of group info seem OK. I use the LDAP uidNumber as the zenphoto user id; that should be OK, as the LDAP ids start at 10000. The rights are hard-coded to ADMIN_RIGHTS for now, but my plan is to later use the group plugin to make the rights customisable from the zenphoto admin interface.

The problem is that when I log in to zenphoto using an LDAP account, there is no cookie set. Or rather, some strategic die() statements show that a cookie is set, with contents ".10000" (so the password part is empty?), but then immediately afterwards, when the cookie is checked for validity, it is deleted.

From browsing through the code a bit, it seems that the function 'setPass' should be called at some point to populate the password part of the cookie. However, I don't know where or how this function should be called.

Do you have any hints on how to continue?

**Comment by sbillard** [comment]
Your analysis is correct. There are two things that will need to be added. 

First the "user" will need some kind of recognizable password hash. Add `$_zp_current_admin_obj->setPass(passwordHash('user', 'LDAP'));` to the ZenPhoto20 code in "handlelogon()" above. The parameters to passwordHash may be any thing that we can re-create later when we are checking cookies.

Then we need to extend the `checkCookieCredentials()` function to recognize the above cookies. Add

`	function checkCookieCredentials() {
		list($auth, $id) = explode('.', zp_getCookie('zp_user_auth') . '.');
		
if ($auth == passwordHash('user', 'LDAP')) {
/setup the user object same as in handlelogon()
}

		$loggedin = zp_apply_filter('authorization_cookie', $loggedin, $auth, $id);
		if ($loggedin) {
			return $loggedin;
		} else {
			return parent::checkCookieCredentials();
		}
	}`

**Comment by sbillard** [comment]
There is at least one other place that the user's ID is used that we will have to address. That is database refreshes. These validate things like the link between objects and users. Won't be an issue so long as the users all have ADMIN_RIGHTS, though. Might be other places as well, I will do some research and add some functionality so it can be addressed.

**Comment by sbillard** [comment]
I am adding a new method to the `_Autority` class: `validUserID($id)` This method will return true if the $id is a valid user id. You can add to your class:

```
function validUserID($id) {
  if ($id >= 10000) {
    return true;
  }  else {
    return parent::validUserID($id);
  }
```

This will be in the next support update. It should take care of all the ID validity issues.

**Comment by ariep** [comment]
Thanks for the quick reply! Following up on this.

> Add `$_zp_current_admin_obj->setPass(passwordHash('user', 'LDAP'));` to the ZenPhoto20 code in "handlelogon()" above.

Could it be that it should be `$_zp_current_admin_obj->setPass('LDAP');` instead? This seems to work.

With these changes, I get "Fatal error: Call to a member function getLanguage() on a non-object in /mnt/data/var/www/pixra/zp-core/auth_zp.php on line 95". It seems that the global variable `$_zp_current_admin_obj` is not set. It is set by the new `handleLogon()` function, but not by the new `checkCookieCredentials()`. Should my `checkCookieCredentials()` call `checkAuthorization()`, like the base class version does? And if so, should `checkAuthorization()` also be overridden, or can I leave it as it is? I'm not quite sure what it does.

**Comment by sbillard** [comment]
Yes, I did not research enough. The setPass() method does do the encryption of the password.

Probably what you should do is remove the override of `checkCookieCredentials()` and instead override `checkAuthorization()`

```
function checkAuthorization($authCode, $id) {
  global $_zp_current_admin_obj;
  // figure out what the candidate user is based on the id and store in `$username`
   if ($auth == passwordHash($username, 'LDAP')) {
    //setup the user object same as in handlelogon()
    return $_zp_current_admin_obj->getRights()j;
  }
  return parent::checkAuthorization($authCode, $id);
}
```
$username will need to be the username of the user associated with the id as set in `handleLogon()`.

Sorry for the mis-steps. But we are exploring new territory. When this is all done I hope you will share the code for others to use.

**Comment by ariep** [comment]
Nice, it seems to work now. This is what I have so far.

```php
<?php

/** class-auth.php**/

require_once(SERVERPATH . '/zp-core/lib-auth.php');

define('LDAP_DOMAIN','localhost');
define('LDAP_BASEDN','dc=rpi,dc=swinden,dc=local');
define('LDAP_GROUP','users');

class Zenphoto_Authority extends _Authority {
    function handleLogon() {
        global $_zp_current_admin_obj, $_zp_loggedin;
        $user = sanitize(@$_POST['user'], 0);
        $password = sanitize(@$_POST['pass'], 0);

        $_zp_loggedin = false;

        $ad = ldapInit(LDAP_DOMAIN);
        $userdn="uid={$user},ou=Users," . LDAP_BASEDN;

        // We suppress errors in the binding process, to prevent a warning
        // in the case of authorisation failure.
        $bindResult = @ldap_bind($ad, $userdn, $password);
        if (!$bindResult)
        {
            // If the authorisation failed we try the standard logon, e.g.
            // for a master administrator.
            echo 'Could not bind to LDAP.';
            $_zp_loggedin = parent::handleLogon();
        }
        else
        {
            $group = ldapSingle($ad, '(cn=' . LDAP_GROUP . ')',
                'ou=Groups,' . LDAP_BASEDN, array('memberUid'));
            if (is_null($group)) { return false; };
            $members = $group['memberuid'];
            unset($members['count']);
            $isMember = in_array($user,$members,true);

            if ($isMember)
            {
                echo "You're authorized as " . $userdn;

                $userData = ldapUser($ad, "(uid={$user})");
                if (is_null($userData)) { return false; }
                list($adminObj,$rights) = setupUser($userData);
                $_zp_current_admin_obj = $adminObj;
                $_zp_loggedin = $rights;
                parent::logUser($_zp_current_admin_obj);
            }
            else
            {
                echo 'Authorization failed';
            }
            ldap_unbind($ad);
        }

        return $_zp_loggedin;
    }

    function checkAuthorization($authCode, $id) {
        global $_zp_current_admin_obj;
        $ad = ldapInit(LDAP_DOMAIN);
        $userData = ldapUser($ad, "(uidNumber={$id})");
        ldap_unbind($ad);
        if (!is_null($userData))
        {
            $goodAuth = Zenphoto_Authority::passwordHash($userData['uid'][0],'LDAP');
            if ($authCode == $goodAuth)
            {
                list($adminObj,$rights) = setupUser($userData);
                $_zp_current_admin_obj = $adminObj;
                $_zp_loggedin = $rights;
                return $_zp_current_admin_obj->getRights();
            }
        }
        return parent::checkAuthorization($authCode, $id);
    }

}

function setupUser($userData) {
    $user = $userData['uid'][0];
    $id = $userData['uidnumber'][0];
    $name = $userData['cn'][0];
    if (isset($userData['email'][0]))
    {
        $email = $userData['email'][0];
    }
    else
    {
        $email = null;
    }
    $rights = ADMIN_RIGHTS;
    $groups = 'users';

    $adminObj = Zenphoto_Authority::newAdministrator('');
    $adminObj->transient = true;
    $adminObj->setUser($user);
    $adminObj->setName($name);

    $pass = 'LDAP';
    $auth = Zenphoto_Authority::passwordHash($user,$pass);
    $adminObj->setPass($pass);

    $loggedin = $rights;
    $adminObj->setRights($rights);
    $adminObj->setEmail($email);
    $adminObj->setID($id);
    $adminObj->setGroup($groups);

    return(array($adminObj,$rights));
}

class Zenphoto_Administrator extends _Administrator {
    function setID($id) {
        $this->set('id', $id);
    }
}

/*
* This function searches in LDAP tree ($ad -LDAP link identifier),
* starting under the branch specified by $basedn, for a single entry
* specified by $filter, and returns the requested attributes or null
* on failure.
*/
function ldapSingle($ad, $filter, $basedn, $attributes) {
    $result = ldap_search($ad, $basedn, $filter, $attributes);
    if ($result === FALSE) { return null; }
    $entries = ldap_get_entries($ad, $result);
    if ($entries['count'] != 0) { return $entries[0]; }
    else { return null; };
}

function ldapUser($ad, $filter) {
    return ldapSingle($ad, $filter, 'ou=Users,' . LDAP_BASEDN,
      array('uid','uidnumber','cn','email'));
}

function ldapInit($domain) {
    $ad = ldap_connect("ldap://{$domain}") or die('Could not connect to LDAP server.');
    ldap_set_option($ad, LDAP_OPT_PROTOCOL_VERSION, 3);
    ldap_set_option($ad, LDAP_OPT_REFERRALS, 0);
    return $ad;
}

?>
```

Let me know if you want me to try something.

It would be nice to be able to drop the automatic ADMIN_RIGHTS, but I'm not sure what would need to be changed, given your remark about database refreshes e.a..

This version is specific to posix-style users and groups; it will no longer work with AD. Perhaps both versions can be offered side-by-side. It would be difficult for me to generalise to a version that can do both (and perhaps other) configurations, as I have no way of testing.

**Comment by ariep** [comment]
Hm, there is a problem with the XSRF protection.

When I try to change options in the backend, I get
> “saveoptions” Cross Site Request Forgery blocked.

Could this be a related problem?

**Comment by sbillard** [comment]
Well done. 

The XSRF probably is related. The cross reference protection generates a token based in part on the $_zp_current_admin_obj. So all instances where these are created need to do exactly the same thing. Right off hand I don't see why they would not be the same, though.

I suggest you do a `debugLogVar('admin object',$_zp_current_admin_obj);` in the function getXSRFToken() [functions.php] to see what things look like. 

Since you are assigning the user to a group we can probably fetch the rights from the group. There is a method in the user_groups plugin ` user_groups::merge_rights($adminObj, array('users'))` that will accomplish this presuming the group 'users' is defined and the plulgin enabled. Use this in lieu of setting the group and rights.

I think that we can just point out that this version is for posix-style users and groups and let someone who knows/wants Active Directory make and test the needed modifications.

**Comment by sbillard** [comment]
I think it is time to collaboratively make these changes with the help of GitHub. So I have created a development branch at https://github.com/sbillard/ZenPhoto20-DEV/tree/LDAP and made some changes both to your code above and to the supporting ZenPhoto20 code.

Please see how that branch works. (I doubt it fixes the cross site reference issue, but it might.) 

You can clone this branch and make push requests to update it.  The script is in "plugins/alt" named "LDAP auth example.php". Naturally you will need to copy it as "class-auth.php" to activate it.

**Comment by ariep** [comment]
OK, will do. I already had some changes of my own, allowing to map multiple LDAP groups to corresponding zp user groups. I will merge these with your new version (and try to comply with your code style this time ;-) ).

By the way, what is the best way to deal with updates of the code in an existing installation? For now, I can just delete my old copy of zenphoto and clone the new branch, as my installation does not contain any data yet. But what if you have data, and want to pull changes in the code? Can you just pull the changes and re-run the setup process?

**Comment by ariep** [comment]
Looking at the debug log for the XSRF problem now.

(BTW, the action I tried to perform this time was deleting the debug log – some irony there.) I get 10 almost identical debug log parts (from 10 calls to `getXSRFToken()`, I guess). Some of these 10 are pairwise identical, partitioning them into three groups that differ only by
1. the header line
`{21032:Thu, 23 Jul 2015 10:56:07 GMT}`, in which both the number and the date vary; and
2. the "passupdate" property in the "updates" part, which varies by a few seconds.

Should these 10 copies all be identical? If not, what should I look for?

**Comment by ariep** [comment]
OK, I went ahead and fixed it. I hope I didn't compromise security along the way; please review.

I changed the `setPass()` function to
```php
        function setPass($pwd, $update = true) {
                $hash_type = getOption('strong_hash');
                $pwd = Zenphoto_Authority::passwordHash($this->getUser(), $pwd, $hash_type);
                $this->set('pass', $pwd);
                if ($update) {
                        $this->set('passupdate', date('Y-m-d H:i:s'));
                }
                $this->set('passhash', $hash_type);
                return $this->get('pass');
        }
```
and call it with $update=false from the LDAP `setupUser()` function. With this, the XSRF protection does not trigger.

Wthat is the goal of storing the password update date? IS it part of the XSRF protection, or merely info for the user?

**Comment by sbillard** [comment]
Best way to update (presuming we have to go from the branch rather than the extract.php script) is to copy the new branch files over the old install and run setup. 

The password update is so that a site can implement password expiry. So for LDAP it is not meaningful and can be set to some constant. The setUser() method can simply store NULL there, I think, then there is no need to change setPass().

**Comment by sbillard** [comment]
I have cobbled up a debug version of the script so that I can force a login to work.

That enabled me to do all sorts of testing. I have found numerous issues both with the script and with some ZenPhoto20 handling of the foreign user. These are all corrected in the current LDAP branch.

I would be happy to work on binding LDAP user groups to ZenPhoto20 user groups, but I need to know how the LDAP groups are presented. My thoughts are that the ZenPhoto site should define groups with the same names as the potential LDAP groups. Then the binding is pretty simple. Just supply the group names in the last parameter of `user_groups::merge_rights($adminObj, array(ZP_GROUP));` It would even be possible to just pass whatever LDAP groups the user is in and ignore them if they are not valid ZP20groups. [that requires a small modification to the ***user_groups*** plugin.

**Comment by ariep** [comment]
> I would be happy to work on binding LDAP user groups to ZenPhoto20 user groups, but I need to know how the LDAP groups are presented. My thoughts are that the ZenPhoto site should define groups with the same names as the potential LDAP groups. Then the binding is pretty simple. Just supply the group names in the last parameter of user_groups::merge_rights($adminObj, array(ZP_GROUP)); It would even be possible to just pass whatever LDAP groups the user is in and ignore them if they are not valid ZP20groups. [that requires a small modification to the user_groups plugin.

I already have a working version with a slightly different approach. Let me know what you think. My version has two separate group configuration options:
1. Group mappings, that map LDAP group membership to zenphoto group membership. In my setup it is inconvenient to use the same group names for both, so I have an actual mapping, parametrised by a configuration setting that should be an indexed array `"ldapGroup" => "zpGroup"`.
2. Authorising groups: I don't want to allow all my LDAP users to be able to log in on zenphoto. Therefore, my code allows setting a list of LDAP groups and logging succeeds only if the user is a member of one or more of these groups.

I want to merge my version again with your changes before I put it on github. I'm on vacation, mostly without internet, starting tomorrow, so it will be a little while before I can get back to this – probably until the first week of August.

**Comment by sbillard** [comment]
Sounds good. There is no hurry on the merge. Enjoy your vacation.

Also there is no problem with LDAP group not authorized. If none of the groups match a ZP20 group then the rights will be 0 and the user not logged in. As to the group mapping, that can work, just to me seems an over-complication. Just as easy to create same-named ZP20 groups for the LDAP groups you want to allow. Only issue might be if LDAP has a group you don't want but that is same-named to a ZP20 group you want to keep.

Anyway with my current implementation all you have to do is return the ZP20 group names that you want the user to be assigned to. (Or an empty array if he should not be logged in.)

**Comment by sbillard** [comment]
If there is no zpGroup mapped (i.e. the $groups variable is empty) then there will be no rights assigned to the user so the login will fall through to the ZP default. SO just the LDAP->zpGroup mapping is all that is needed.

**Comment by ariep** [comment]
Your current version is actually improved to the point that I have nothing left to merge. (I had factored out some common code from the authentication test on the one hand and the group membership query on the other, but now that the former turns out to be superfluous, this is moot.)

I would prefer to keep the group mapping as it is, i.e., with the possibllity of differing names. One advantage of this is that one can map existing LDAP groups to the built-in zp groups (viewers, administrators, etc.). This makes it very easy to get started quickly.

One more question (only tangentially related, sorry): I'm having trouble to understand and administer the rights of groups and ownership of albums. Can I take my questions to the zenphoto forums <http://www.zenphoto.org/support/>? Or is ZenPhoto20 too different?

**Comment by sbillard** [comment]
ZenPhoto20 is a spinoff from Zenphoto, so for the most part things work similarly. BUT, and it is the big BUT, I have continued to fix bugs improve the way things work so they are drifting apart. You can ask questions on our Googld Grouss forum: https://groups.google.com/forum/#!forum/zenphoto20

I have one more change to add that I would appreciate your testing. (I have built a simulated LDAP server, but it is reverse engineered so not a valid test vehicle for the LDAP bits.) I am adding an ability to have a LDAP "reader" user/password in case the anonymous searches are prohibited.

The other question  I have is what the differences between the posix LDAP and Active Directory LDAP are. It might just be possible to make this script support both.

Finally, take a look at the doc comments and add to them as you see fit. Probably by the end of this week we can make this official.

**Comment by sbillard** [comment]
A further question on LDAP servers. Is there the concept of a "logged on user"? It would be nice to implement "single logon" if such exists. All we really would need is to be able to query the LDAP server and ask if there is one or more already logged in users of the client system. Then we could bypass the logon and cookie requirements we currently need.

**Comment by ariep** [comment]
>I have one more change to add that I would appreciate your testing. (I have built a simulated LDAP server, but it is reverse engineered so not a valid test vehicle for the LDAP bits.) I am adding an ability to have a LDAP "reader" user/password in case the anonymous searches are prohibited.

I tried this: I entered my usual LDAP username and password as binding authentication data. It failed though: debug.log says "LDAP reader authorization failed.". However, I would guess that my LDAP server is not set up to work this way – allowing binding as a "posix user". It would be better to have this tested by someone who actually uses binding authentication.

> The other question I have is what the differences between the posix LDAP and Active Directory LDAP are. It might just be possible to make this script support both.

Well, I don't know myself, but a few days ago someone on the zenphoto forums asked about this:
<http://www.zenphoto.org/support/topic.php?id=1409115>. Maybe you can cooperate with him/her to do the same for AD as we have done for openLDAP.

> Finally, take a look at the doc comments and add to them as you see fit. Probably by the end of this week we can make this official. 

What do you mean by the "doc comments"?

> A further question on LDAP servers. Is there the concept of a "logged on user"? […]

No, not that I know of. Even if the LDAP server would have a "currently logged in" field, you would still need some SSO mechanism to verify that the user is indeed the one she claims.

BTW, there was one change I needed to make to get the LDAP stuff to work again: the $userData variable contained a 'userPassword' field from the LDAP server, but it would not always be included in the query results for some reason. This caused a mismatch between auth tokens (as a hash of the userData is used as a password for the cookie) and thus authentication failure. I submitted a pull request <https://github.com/sbillard/ZenPhoto20-DEV/pull/1> with these changes.

**Comment by sbillard** [comment]
'What do you mean by the "doc comments"?`

The comment block at the beginning of the script.

**Comment by sbillard** [comment]
I think that this is just about ready for prime time. I did make some changes needed for fixing #428, so a final verification is needed. So, if you will make a final check on things we will be good to go.

**Comment by ariep** [comment]
As a test, I tried a fresh install (of version 39ba5cf2). There is one small glitch in the options handling part:
``` NOTICE: "Undefined variable: ldap" in /mnt/data/var/www/ciprpixra/plugins/alt/class-auth.php on line 94
 URI:/ciprpixra/zp-core/admin-options.php?action=saveoptions
 user:admin
  Zenphoto_Authority->handleOptionSave called from processCustomOptionSave (admin-functions.php [1001])
    from admin-options.php [486]```
This seems to happen if the security options are saved while the user_groups plugin is not activated.

**Comment by ariep** [comment]
Some nitpicks about the LDAP group map setting on the security settings page:
* The templates are included as well. Is this on purpose? I guess there would be no difference in semantics between groups and templates fur this purpose: users that belong to the corresponding LDAP group just get the rights specified by the template. However, this might surprise someone who edits a template, thinking that that can have no direct effect.
* A heading ("LDAP group","Zenphoto20 group") above the two columns in the table of groups would be nice.
* Will setting one of the text fields to the empty string disable that mapping?

**Comment by ariep** [comment]
Hm, there is something weird going on with the login system.
I enabled the user_login-out plugin, to get a "login" link on the front page. When I click on the link I get a login form. However, filling out the form correctly and clicking on the "Login" button, I'm sent back to "http://domain/gallerydir/?userlog=1", and I'm not logged in: there is no settings icon in the top-right corner, and there is still the "Login" link at the bottom of the page.
* It doesn't seem directly related to the LDAP parts, because even entering master user&password gives this result.
* I can get around this by directly entering the URL of an admin page. Then I also get a login form, but that one works (both for the master user and for LDAP users that have admin rights). If I then go to the gallery main page, there is a "Logout" link instead of "Login", as expected.
* This problem only appears when the user_login-out plugin's setting is set to "None" or "Colorbox", not if set to "Form". (BTW, "None" and "Colorbox" appear to do the same thing: display a link "Login" to a login page.)

**Comment by sbillard** [comment]
Including Templates was deliberate. Seemed a useful feature, but I see your point. I think I will remove the templates.

I'll add the headings

Setting the string to empty removes any mapping.

I'll have to look into the user_login-out issue. You should be sent back to the gallery page, but the user should be logged in at that point. What theme are you using?

**Comment by ariep** [comment]
> I'll add the headings

Great.

> Setting the string to empty removes any mapping.

OK, good to know. Perhaps could be worth a sentence of explanation on the option page.

> I'll have to look into the user_login-out issue. You should be sent back to the gallery page, but the user should be logged in at that point. What theme are you using?

The default one: "Basic".

**Comment by sbillard** [comment]
For me the colorbox login form works correctly. The plain link did not. I have changed the link to simply go to the admin pages. I was never able to figure out what was going wrong.

I have also made a major change to the scripts.

They are now a plugin named LDAP_auth. Enable the plugin and LDAP is enabled. Disable it and LDAP is disabled.

**Comment by ariep** [comment]
> For me the colorbox login form works correctly. The plain link did not. I have changed the link to simply go to the admin pages. I was never able to figure out what was going wrong.

OK.

> I have also made a major change to the scripts.
They are now a plugin named LDAP_auth. Enable the plugin and LDAP is enabled. Disable it and LDAP is disabled. Names have also changed.

(Upgrading to this version did not go smoothly: after `git pull` I could not run setup: it would not let me log in. I had to drop the database to reset the admin password.)

This new version gives the following error:
```
Notice: Undefined variable: ldap in /mnt/data/var/www/ciprpixra/zp-core/zp-extensions/LDAP_auth.php on line 107

Fatal error: Cannot access parent:: when current class scope has no parent in /mnt/data/var/www/ciprpixra/zp-core/zp-extensions/LDAP_auth.php on line 109
```
The fatal error occurs because the class `LDAP_auth_options` does not have a parent. I'm not sure which `handleOptionSave` function is supposed to be called there.

**Comment by sbillard** [comment]
Should both be fixed now.

**Comment by ariep** [comment]
Great job, thanks!

**Comment by sbillard** [comment]
I'va also incorporated your other fixes (with some improvements.)

I hesitate to say things look ready since that has been such a disaster in the past. But maybe this time....

I'll let you have a bit more time for testing since you are doing such a good job of finding problems. Let me know when you think you can't break anything.

**Comment by ariep** [comment]
It's more like problems are good at finding me, from my point of view... :-)

OK, one more bug that struck me (again not LDAP-related): some unpublished albums suddenly turned out published. Not so nice. It happened again and again, especially if you're changing some other properties of the album; the "published" checkbox is suddenly on again.

After hunting through the code for a very long time, the culprit turns out to be this guy:
```php
        function getPublishDate() {
                $dt = $this->get("publishdate");
                if ($dt == '0000-00-00 00:00:00' || is_null($dt)) {
                        return $this->getDateTime();
                } else {
                        return $dt;
                }
        }
```
This is called from the album edit form and the result is used as the current value of the publication date. If there is no pubdate set, then the above function gives back the value of the `date` property of the album object, which I guess is the creation date of the album. When you then save the form, this becomes the publication date. Next, because the creation date is before now, the publication date has passed and the album is automatically set to published. Ouch.

I would like to change the above function to return null if the pubdate is in fact null, but there are so many uses of this function that I'm not prepared to do this without your opinion.

**Comment by sbillard** [comment]
How about only supplying the current date if the object is published? That seems to work. Change is up.

**Comment by ariep** [comment]
That would fix this problem, yes. I'm not sure if this gives the right semantics, though. What is the meaning of the publishdate field? When the object is not published, it is the time when the object must be published. But what if the object /is/ published? There are many possible meanings, for example:
1. It is the date when the object was first published.
2. It is the date when the current period of being published began.
3. If the object was published automatically by preset date, it is that date. Otherwise, It is the date when the object was created.
This fix seems to choose 3. But I'm not sure if this meaning is also followed in other places in the code.

Also, dynamic albums apparently have the field `date` set to null. That means that the fixed `getPublishDate` function can still give back null, and it further complicates the meaning of the publishdate field.

Anyway, I'll happily work with this fixed version. Just something to think about.

**Comment by sbillard** [comment]
When an object is published the date is the last publish date. When not published it is the scheduled publish date or empty if not scheduled. The reason for the code is that publish date is a "new" attribute for images and albums, so might be null even though the object is published.

**Comment by sbillard** [comment]
The implementation is now in the main-stream. For problems please now open new issue tickets.
