### ISSUE TITLE
enhancement: print tag links and mod rewrite

### ISSUE THREAD

**Issue by Jens2014** [ZenPhoto20/ZenPhoto20#358]
Hi,
using mod rewarite activated I can use the URI for tags: `page/search/tags/word/` and it works perfect.
Currently the tag links where printed as something like `page/search/tags/14.616e696d616c73/`. Could you please adjust the printed tag link to `page/search/tags/word/`? I think this would be an improvement in the meaning of usability and SEO.
Thanks, Jens

**Comment by sbillard** [comment]
The insertion of "word" after "tags" is redundant and not SEO. But if you really want this you can alter your site to do so. Use the rewriteTokens plugin options to change the token for "tags".

**Comment by Jens2014** [comment]
I think I did not described my suggestion good enough.
Imagine you have a tag "animals". Actual the link to the images tagged with "animals"  will be printed with some kind of identifier: `page/search/tags/14.616e696d616c73/` (real world link from my site) and not `page/search/tags/animals/` (what I would expect as a link). May it be that it is unicode encoded here?

**Comment by sbillard** [comment]
The encoding is deliberate since the tag may contain any character, including ones that will break URLs. While it is theoretically possible to know when the URL will break, practically speaking it is not, so all the tags are encoded. But it is true that if you create a link with un-encoded tags (and the tags do not have any of the offending characters) the link will work. 

Typically these links are not exposed. Normally just for pagination. Actual searches post the data so the tags do not show at all.

**Comment by Jens2014** [comment]
Ah ok. Now I understand the reason behind. Thank you for your explanations. Best regards, Jens
