### ISSUE TITLE
GPS - even little bug

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#363]
ZP20 1.1.7.0
Showing in map is OK.

But when showing metadata (frontend and backend)...:
![metadata](https://cloud.githubusercontent.com/assets/7648991/7769006/d54294b4-0080-11e5-9ec2-6880fa0af693.jpg)

Not serious for me...

**Comment by sbillard** [comment]
Can you please supply a test image for this? I do not see any issues with the images I have.

Also try refreshing your metadata and see if that makes a difference.

**Comment by sbillard** [comment]
I have a theory on this. Maybe the decimal separator character is different for MySQL and PHP. If so saving the reference in the database might truncate the values. I have changed https://github.com/sbillard/ZenPhoto20-DEV/ to store these as character strings. See if that makes a difference.

**Comment by Mates-K1** [comment]
I think it is related to issue #327, before reparing this issue it was ok, bud wrong in googlemap, now it is  vice versa.

Ok, I will test it.

**Comment by Mates-K1** [comment]
Neither refreshing metadata nor actual DEV didnt help

Example photo:
http://skaut.zamberk.cz/galerieonline/index.php?album=stredisko/vypravy/2015_03_21_rytiri&image=002.jpg

You can download this photo in frontend (link below photo).

Your account is still ON. :)

**Comment by sbillard** [comment]
Sorry, I should have mentioned that you need to run setup. If you have not done so with the new code, please to and then run a metadata refresh.

**Comment by Mates-K1** [comment]
Done... and it works. :+1: 

Thanks. :)

**Comment by sbillard** [comment]
It seems to me that there is something wrong with your site setup for these problems to occur. Granted, we can make sure that things work no matter what, but there might be other software or other issues because of this.

As best as I can surmise there is a problem with dealing with the decimal separator character. We saw this with the *float* function previously. Now it appears that the database and PHP do not agree on what the character is. This caused the data being stored in the database to be truncated after the "decimal separator".

The fix has been in both cases to "bypass" the defined decimal separator and do what we KNOW is right. In the first case by using a brute force *float* function. In the second place by changing the field from a number to a character string.

Just FYI.
