### ISSUE TITLE
Idea: better protection against hotlinking

### ISSUE THREAD

**Issue by ariep** [ZenPhoto20/ZenPhoto20#429]
By default, direct access to the image files is not prevented. There is a .htaccess template to do so,  linked to from <http://www.zenphoto.org/news/htaccess-against-hotlinking>, but that only checks the HTTP_REFERER, which is easy to fake.

I have an idea for another form of protection against hotlinking:
* automatically add a .htaccess file to every subdirectory of "albums" and "cache", which checks for the presence of a cookie containing a special access token.
* when a user logs in to zenphoto (or enters an album password), check which albums the user may view, and for every one set a cookie with the corresponding access token.

Does this seem viable? Implementing this requires a bit more understanding of the ZP code base than I currently have, but if someone could give me some pointers, perhaps I'll have a go at it.

**Comment by sbillard** [comment]
The problem I see is that cookies expire so it would really be necessary to set the cookie whenever the user visits the site.

If you select "protected view" for the full image and set a password then only users with full image rights or who know the password will be able to load the image. This does presume that the album folder is somehow protected--either with .htaccess deny all or by not being in the WEB path. "Protected view" would be needed for the cookie implementation as well.

In addition, some javascript based utilities may not work if they do not handle image processor URIs as images. (This will be true no matter how the blocking is implemented.)

**Comment by sbillard** [comment]
I have considered this a bit more. There would be no better hotlink protection based on cookies vs. based on HTTP_REFERER. Both are easily forged. `.htaccess` files are "universal" in that since they are stored on the server they apply to all visitors equally. Thus the "value" of the cookie would need to be a constant, so could be easily guessed as well by legitimately visiting the site and capturing the cookies that are set.

This implementation would require some considerable overhead as well--The code would have to process the complete set of albums and store cookies for the appropriate ones each time a page is loaded. (There is no guarantee that a page will not reference some album not easily associated with it--for instance a news article with an imbedded image.)

In my opinion this approach adds much overhead and is not justified by any increased protection.
