### ISSUE TITLE
Non english character in name of image

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#537]
By my oversight I had czech character in one of my file and file didnt show. 

```
{40014:Sun, 18 Sep 2016 11:53:32 GMT}
  UPOZORNĚNÍ UŽIVATELE: "Bad filename suffix in newImage(zapis_jedn)" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 67
 URI:/galerieonline/1_oddil_skautu/vyjezdni_zasedani/vz_2003p/bondy/
 IP `87.249.128.78`
 uživatel:Mates
 Vzhled:zpArdoise
  trigger_error called from zp_error (functions-common.php [67])
    from newImage (class-image.php [60])
      from getAlbumGeodata (googleMap.php [295])
        from printGoogleMap (googleMap.php [399])
          from include (album.php [149])
            from include (index.php [148])
              from index.php [28]
```

I know it is not good to have non-english character in name of file. I dont know this is "standard" behavior of ZP or some little bug. Maybe this will help you.

**Comment by sbillard** [comment]
This message comes when the file suffix (e.g. .jpg, .png, etc.) is not supported by the graphics library. So I guess the question is what was the file name of the image?

One thing that might cause this is a character set problem with your database. MySQL will discard characters starting with any "invalid" character. Check that your encoding for the table--it should be UTF8 Unicode CI

**Comment by Mates-K1** [comment]
File name were `zapis_jednáni_vz_7.pdf` and `zapis_jednáni_vz_7.jpg`.
There were `á` in names that make problems.

**Comment by sbillard** [comment]
These characters generally do work in Zenphoto20. However often servers have difficulties with them. One possibility is that the character set of the filesystem is not properly known to Zenphoto20. For instance if Zenphoto thinks it is working with an ASCII file system it will present an ascii á but if the file system is utf8 that will fail. Also check your database for the truncation I mentioned above.

**Comment by sbillard** [comment]
Another area of problem often is the encoding of the URLs.  Some servers expect UTF8, others ASCII. If that is wrong the file names get corrupted. But these character set issues are probably not the problem since there should be no diacritical marks in the suffix and PHP is searching for the period separator from the back of the string forward.

**Comment by Mates-K1** [comment]
DB has utf8_unicode_ci, server has UTF-8 Unicode (utf8).

All works. I'll just make sure I do not have files with non-english character. I thought that the bug was on my side.

**Comment by sbillard** [comment]
It really should work. Works on my test sites. But often there are server issues that we cannot fathom.

http://testalbum.sbillard.org/testing-images/tig%C3%A9r.htm

**Comment by Mates-K1** [comment]
Your test works for me. :)  Your adress ends *.html, mine *.jpg. (mod_rewrite on, but mod_rewrite suffix empty). When I change name to name wiht `á`, whole album doesnt work.

**Comment by sbillard** [comment]
The image has the é in the name, so that it displays means the name works on this server. Sorry I don't really have any good ideas on how to make it work for you other than avoiding the diacritical marks. Something in your server configuration.

One thought, though, try a .html as a mod rewrite suffix. Some servers "know" that things ending in .jpg are images and don't properly run scripts. Just a long shot guess, though.
