### ISSUE TITLE
Defining userrights per album

### ISSUE THREAD

**Issue by jeldriks** [ZenPhoto20/ZenPhoto20#539]
Like the ability for setting which user can manage an album, I'd like to assign specific rights per usergroup on the album editing page. Like for hiding an album from specific usergroups.

Thanks for your time and effort in this great project!

**Comment by Mates-K1** [comment]
I think you can make new usergroup with album specific rights. I use this in my gallery.

Admin - Groups - type name of new group, on right side Managed albums. You can set rights to specific albums.

**Comment by sbillard** [comment]
Mates-K1 is correct. User groups can have the same kinds of rights assigned as individual users. As to hiding an album, please note that the only control on visibility is the published status of the album and the user/user group rights to view unpublished albums. There is not a concept of "hiding."

Do these answers address your issues?

**Comment by jeldriks** [comment]
Thank you very much for your replys!
I think, it would be more useful to be abled to set the rights on the page of each album, as well, because it reduces the steps to get to the desired result. Would it be possible to implement this feature, please?

**Comment by sbillard** [comment]
I am not sure how this request would work. The paradigm of rights is really user (or user group) based. They are the things a user is permitted to do/see. Albums really do not have rights. 

Besides which there are both global rights and managed album specific rights. The global rights override whatever might be set for the managed album specific right. It would be impossible to summarize various user global rights on an album page. In addition, for implementation performance reasons, only global albums can be managed so the placing rights on the album page would be confusing because they would have to be disabled if the album is not global.

**Comment by jeldriks** [comment]
Sorry, I didn't express myself clearly enough. The basic functionality I'm requesting is the duplication of the managed album rights from the user group page to the album page.
Therefore the assigning of rights would be other way around: On album page the title of the section wouldn't say "Managed albums" but "Managed by" and instead of albums there were checkboxes next to all the user groups.

**Comment by sbillard** [comment]
I did understand your request. Perhaps I have not explained the difficulty.

To best understand please look at the rights section for a user. There are global album rights and possible individual album rights that may be a subset of these global rights. It is not a simple check box. To set these rights from the album point of view would require presenting the full set of choices. While this is technically feasible the practicality is minimal. 

Also please note that users may be members of more than one group. Perhaps the simplest solution would be for you to create a group that deals exclusively with album management and assign users to that group as appropriate. They can also be members of other groups to give them additional rights.

**Comment by sbillard** [comment]
I have given a bit more thought to this. My primary objection is that this feature will add considerable overhead to the album page because of the complexity of providing the user/group/template list candidates. It could also be a little confusing to use because the "checkboxes" would actually be for album edit, album upload, and viewing the unpublished items in the album. The last two would not necessarily be present based on the user/group/template settings of "upload" and "view unpublished." 

The "solution" to the performance issue would be to make the feature a plugin. Then only those who thought it worth the costs would enable it. There is currently a filter available for the "Utilities" section of the album tab. That would be where the feature would appear. It would, of course, appear only for the first level albums since those are the only ones that may be managed. Presumably similar functionality should apply to categories and pages.

It would not be a trivial effort to implement this. So I would like to know how many would find it useful.

**Comment by nerdykit** [comment]
One vote that it would not be useful to me.  I realise that what you want to count are votes that it WOULD be useful but my response is “no thanks, I can’t see myself using such a plugin”.  Since you’re reading this, just want to register my thanks to you for all the work you do on ZenPhoto20, it’s great that you are so responsive to any suggestions or to those who find any bugs.

Kit

**Comment by sbillard** [comment]
@nerdykit:  Thanks for your comments. Good to hear your appreciation.

**Comment by sbillard** [comment]
As there has been no further discussion, I will close this ticket. For now, at least, this feature is not on the list of future enhancements.
