### ISSUE TITLE
A back button top

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#565]
Delete the top links and replace with a top left bottom button, And generalize it to all pages that have content below the waterline
![sans titre](https://cloud.githubusercontent.com/assets/25553946/23579229/3b5bac9e-00e9-11e7-924d-75716ad839ab.png)

**Comment by sbillard** [comment]
First, it would be helpful for you to identify the page your are citing. Please understand that I have not memorized the looks of all the pages so as to be able to identify them by site.

Second, I do not understand the meaning of "replace with a top left bottom button." Nor do I know what you intend by "generalized to all pages that have content below the waterline."

**Comment by zorodimanche** [comment]
Hello billiards First of all thank you for your reaction the page you see above is page of the statistics of the gallery.

Then, what I mean is that for example when a user desends with his mouse automatucially the back button top of page is displayed: Scroll to top.
For example: https: //codyhouse.co/gem/back-to-top/

**Comment by zorodimanche** [comment]
Tank you very much @sbillard it works.

**Comment by sbillard** [comment]
Sorry, but I do not know how to contact you otherwise from this ticket system.

I have noticed that you declared your intent to do some translations for Zenphoto on the Zenphoto ticket system. I would caution you to be aware that this is an effort of considerable stature. Also the Zenphoto team has been speaking of a "new version" for the past couple of years. You may have noted reference to this on some of your tickets. This version is being developed off-line so no one has any view of what will come. (An interesting tactic for an "open source" project.) 

One claim is an extensive redo of the administrative pages. That is likely to impact the text on the pages as well, perhaps invalidating much of what you will be translating. Of course so long as the development is kept secret we have no way of knowing. It may be a "yuge" change (in the words of the American President) but who knows.

ZenPhoto20, on the other hand, has a strict policy of an open and transparent development process. And as you know from some of the problems you have reported, we are more open to making changes in the present. (You have to suppress changes to the current if you are abandoning it for a different implementation.)  

I solicit you to make your translations for ZenPhoto20 and join our branch of the software.Any changes to the administration panels will be incremental and you will see them as they develop.
