### ISSUE TITLE
Getting a new page warning on exit

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#569]
When I exit certain pages (the image sheet in album edit, individual image edit and album edit) I get a warning about "This page may have been changed do you really want to exit" even if I've just arrived on the page and done nothing to change it.  Earlier versions of ZP20 did not do this.  Is this a setting that I can turn off, it is wrong most the time and quite annoying.

Thanks

![screenshot 2017-03-06 at 4 34 00 pm](https://cloud.githubusercontent.com/assets/3220548/23636906/41e6c18e-028d-11e7-9c5c-91199a2659d1.jpg)

**Comment by sbillard** [comment]
This detection has been around since the inception of ZenPhoto20. As with your other ticket, From what version were you coming and to which version?

The most likely cause of the problem is that your browser has managed to fill in a user/password field somewhere (even when hidden.) Other things I have seen are when you move your mouse through the edit field of a TinyMCE edit text area TinyMCE will consider the data changed even if you have not done anything.

There is no option to turn off the check currently. You can edit the printAdminHead() function in admin-functions.php and delete the line that reads `$('form.dirtylistening').dirtyForms();` to disable this.

What browser are you using? I am not seeing this behavior with Chrome on my sites. Does this happen on every album and image page? If not, can you determine any differences?

**Comment by nerdykit** [comment]
I'm using 1.3.5.0 and have not changed anything since this version came out and I updated to it.  Will do some tests to see what pages it occurs on and what triggers it.  My browser is the mac version of Firefox.  Will try a couple of other browsers to see if the behaviour changes.

Thanks

**Comment by sbillard** [comment]
One thing to check. Try disabling TinyMCE and see if there is a problem. There may be an issue of TinyMCE behaving badly.

**Comment by sbillard** [comment]
So I have done some testing. I can't really get a handle on the problem, but I have some theories.

First, things seem to work if TinyMCE is not enabled.

I set up debugging for dirtyForms and all I could see is there were sometimes "undefined" fields and also a field with a name like "MCE_29." But there was no debugging that showed these (or any other field) being set dirty.

I did notice that the zenpage admin pages did not re-direct after an "apply" which should be standard practice to insure a clean slate on the page load. I have changed this so that the reload happens. This seems to fix the problem, but since the problem was quite ethereal for me I really can't say we are done.

Anyway, there is now also an option to disable dirtryForms if all else fails.

One possible correlation to when the problem occurred was if multiple TinyMCE windows had data in them. So if that rings a bell with your failures please confirm. (Not that I know how that would cause the problem.)

You can try the DEV build if you like. But understand that there are significant changes that impact the database. You can go forward, but you will have to reload your database from a copy from the 3.5 install if you want to go back. I think the DEV build is stable, buy you never know.

**Comment by nerdykit** [comment]
Thanks for your work on this.  I didn’t manage to find time to experiment but you have.  Yes, turning off TinyMCE via the plugin seems to remove the problem.  Since I don't really need that editing capability, that is what I'll do.  It isn't important enough for me to have to reload data and I have far too many photos in ZP20 so if I lost the database it would be a disaster so I'll wait for the next release version.  Thanks again for all your work on ZP20- your response time on issues is incredible.

KD
