### ISSUE TITLE
How to change album in category

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#574]
How to change album in category; Because for sites that uses zenphoto for wallpapers for example album does not mean anything: to have categorie in place of the albums is more speaking for the users: Nature, Cars, Country ....

**Comment by sbillard** [comment]
I do not think I understand. "Categories" are associated with news articles, not images or albums. 

Perhaps you mean to add "Tags" to your albums and images. You could create a tag for "Nataure", "Cars", etc. and then assign individual albums or images those tags as appropriate. Searches can be done by tags.

Alternatively you could have an album named "Wallpaper" and subalbums named for each of your categories. Place the images in the appropriate subalbum. This way an image could appear in more than one dynamic album by having more than one tag set.

If you choose to use tags you can also create "Dynamic" albums from searches, thus you could create an album named "Nature" that would contain all the images you have tagged with "Nature."

**Comment by zorodimanche** [comment]
Thanks @sbillard for for intervention In fact I want to create a site with categories as in this example below
![zen](https://cloud.githubusercontent.com/assets/25553946/24204779/c9049b12-0f19-11e7-8736-8536b686c01d.png)

**Comment by sbillard** [comment]
You should have no problem doing that by using tags and dynamic albums. Of course the theme would have to be customized to achieve the look and feel you desire.

**Comment by zorodimanche** [comment]
Thank you @sbillard for your answer I will try to see this.

**Comment by zorodimanche** [comment]
Hello @sbillard It is not possible to add it in the backend as in wordpress because many who use zenphoto categorie is more speaking than album car to create files: nature, country, space, sea, computer science, education.

The structure of the url would be: http://example.com/category/united-states/new-york-city/filename.jpg


For example, you can add US and publish articles for New York, Los Angeles, Chicago, etc. This is where you can use the categories of children. United States would become a parent category, and cities may become child categories.


![child-parent-categories](https://cloud.githubusercontent.com/assets/25553946/24790983/b6d08db4-1b78-11e7-8617-3b6c055e876a.png)
![sidebar-categories](https://cloud.githubusercontent.com/assets/25553946/24790991/bcf18720-1b78-11e7-8adf-02f159ea0fca.jpg)

**Comment by sbillard** [comment]
Of course these could be added. I think it unnecessary because tags can be used. Tags are a standard feature of image Metadata. They are called key words. Categories do not exist in Metadata. So you are asking for a deviation from standard. You have not made a case for thins. No other user has requested it (perhaps because it provides no new capability.) 

I suggest you make use of tags. You can certainly imply a hierarchical structure. For instance, Photoshop Bridge does this. But understand that the underlying Metadata definition is a flat structure. 

If you do not have the skills to do this yourself then you should hire someone to do it for you. 

When you are the only one who is asking that should give you the hint that it is not generally useful, so maybe not something that should be invested in by a developer. 

I might add that in your particular case you seem to be straddling the chasm between zenphoto and zenphoto20. If you are not even going to use zp20, why would we be interested in your requests unless they make an actual improvement for everyone? Perhaps you would be better off waiting for the ethereal "big release" of zenphoto.

**Comment by zorodimanche** [comment]
Why ? The next version will contain the categories of images if yes then will be a big step forward.
Then, this post is not for my particular case as I have obsessed the competitors of zenphoto (piwigo, coppernic, wordpress, koken, gallery3) they all have this category function. Thank You.

**Comment by sbillard** [comment]
Consider this a warning.

The Google Groups for ZenPhoto20 is the place for discussing hypothetical enhancements to this software. The ticket system is for posting problems or specific needs. If you continue to misuse the ticket system with requests you do not even intend to use you will be blocked from using the system.

If you prefer the competitors to ZenPhoto20 then by all means please use them.  But if you choose to continue with this software use the features it has.  There are good reasons we have made the choices in how things work. Our users have not complained that they do not meet their needs. There is no point in spending resources on features that no one will use.
