### ISSUE TITLE
Limit bandwidth to unregistered users

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#577]
Limit bandwidth to unregistered users. The webmaster defined the limit in the backend and for users who connected the bandwidth is unlimited.

**Comment by sbillard** [comment]
How would you define bandwidth? Also, what do you propose happen if the bandwidth is exceeded?

**Comment by zorodimanche** [comment]
Thanks to a plugin the webmaster can limit the bandwidth of the users not registered to 2.5mo and if it is exceeded redirect towards page of inscription

**Comment by sbillard** [comment]
You still have not defined what you mean by bandwidth. If it is the traditional meaning then no server side script has the knowledge of what the server is delivering to the browser. (I don't even know what 2.5mo might be, 2 and a half months? Bandwidth is normally measured in gigabytes.)

Perhaps you should re-think your suggestions with an emphasis on what the problem you wish to solve is rather than what you think might be the low-level implementation. For instance your issue on zenphoto_sendmail really should have been a request to manage how the user_mailing_list plugin behaved since that was the real problem.

In the case of bandwidth, if that is really the issue, the only place to address it is with the web server software. For instance you could require your users to log onto Apache. Then with Apache bandwidth management tools you can limit who gets how much traffic. ZenPhoto20 provides a means for single logon using Apache credentials, to the user does not have to log in multiple times.

**Comment by zorodimanche** [comment]
Sorry because I do not have much computer skills and programming skills but when I ask questions like this helps me to learn this is why I say that being wrong is a right, correcting is a duty.

**Comment by sbillard** [comment]
Then perhaps the best approach is to first ask the question on the support group. There is a much bigger audience that might help educate you.
