### ISSUE TITLE
Comment response

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#579]
It's just a ticket to request a small feature. :)

Add the ability to respond to a comment.

**Comment by sbillard** [comment]
Please examine the use of comments with ZenPhoto20. How they are listed, etc. and suggest how one would indicate which comment he is responding to. Note that comments are a string of perhaps unrelated postings ordered by when they were made.

Also, should the response be part of the comment thread or simply an e-mail to the person making the comment? Would anyone be allowed to make the reply? (If the reply is to be an e-mail that would allow spammers to  use your site for their spamming.)

Some careful consideration needs be made for such a feature. If you can come up with a comprehensive set of design features and requirements it can be considered. But what I think you probably want is the equivalent of a bulletin board system. That might be useful, but is not a small project.

**Comment by zorodimanche** [comment]
Once the answer is written there is no mail to send
Since the admin part, we can put terms to be forbidden like url or the word "forest" and the answer should not be seen by everyone until the administrator has authorized the comment.

**Comment by sbillard** [comment]
Sorry, but this is a feature that you desire, so it is up to you to give it detailed specifications. What you have done so far seems to indicate you have not given it much thought. If you do not think you can produce a proper requirements specification you really should not be wasting my time with the request. 

But as to this last comment, it seems to have nothing to do with replying to comments and maybe even does not make any sense. Certainly not without some major assumptions on what you are talking of. So again, perhaps a not so carefully thought out wish. I reiterate: figure out what you want in enough detail that someone else can determine the steps to implement it. That is, make a proper requirements document/statement.

I will close this ticket. If you can get your thoughts together and make a proper requirement please open a new ticket.

**Comment by zorodimanche** [comment]
Could not this be included in the plugin comment_form.

**Comment by sbillard** [comment]
I don't think you understand. I have no idea what you want to do given the sparse information you are willing to provide. I can make some guesses, but that is no way to run a show.

Any changes to this would necessarily be made in the comment_form plugin. But knowing this in no way adds any information on WHAT it is you want to be able to do. So, take a deep breath and think about what you want to be able to do. Then write it down in as much detail as you can so that someone can know what you want without reading your mind.

If you are not willing to take the time to be clear why should anyone be willing to spend time implementing you wants?
