### ISSUE TITLE
Would like to be able to set some albums to showing no date

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#605]
Would like to be able to set some albums, particularly top-level albums to showing no date.  Would like to be able to set dates for other albums.  It may be possible to achieve this request with a setting but if so, I can't find it.

Visible album date seems to be publish date instead of assigned album date.  Publish date is often not when the photos in that album were actually taken.

Thanks

NK

**Comment by sbillard** [comment]
There is an option on the gallery page named "use latest image date as album date" which if set will cause the album date to reflect the date of the most current image. This will typically be the date it was uploaded, although different file systems behave differently. If the option is not set the date will be taken from the album folder. This will typically be the date stamp of the folder from when it was discovered. (Again, filesystems may play their games. Unix file systems will likely change this date whenever an image is added to the folder. But that should not be a problem since the date was captured when the album was first discovered.

If you do a "refresh metadata" on the album and the date of the folder is more current than the date stored in the database, the date will be updated to the folder date.

This date should not reflect the publish date unless albums are published on discovery.

You can clear the date on the admin album page for the album. However, since this field is stored as a "date" field in the database it will be stored as "0000-00-00 00:00:00". I will update the software to return a "False" value it the date is zero. This will have the effect of not printing a date if it has been cleared.

You can also set the date to what you believe is correct and it should persist. (Note the comment about refresh metadata.)

**Comment by nerdykit** [comment]
Thanks.  Your response covers my request.

NK
