### ISSUE TITLE
Exception when searching

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#665]
Latest stable (1.5.1.3).

![9f0a2f7e-76d2-421d-a2cd-723a02905694](https://user-images.githubusercontent.com/7648991/31760126-f187c146-b4b3-11e7-831c-7507cd42e554.png)

After click on exception:
![7c462b42-ee69-4403-ac1c-0dd0b167c205](https://user-images.githubusercontent.com/7648991/31760147-0056fb10-b4b4-11e7-939e-ac7b05d8ef95.png)

This happens when searching "mp4" or "flv".

**Comment by sbillard** [comment]
A few questions, I am having difficulty reproducing this:

What theme are you using? 
Does the failure occur for "jpg"?
Is there anything supplemental in the debug log? (Please reproduce with the site in "debug" mode.)

**Comment by Mates-K1** [comment]
This occure in all themes.

JPG and PDF are OK.

From debug:
```
{29160:Thu, 19 Oct 2017 15:46:12 GMT} ZenPhoto20 v1.5.1.3
  EXCEPTION (0): "Call to a member function isDynamic() on null" in /data/web/virtuals/172972/virtual/www/zp-core/class-image.php on line 1060
 URI:/page/search/
 IP `37.48.8.4`
 uživatel:Mates
 Vzhled:copy_of_zpardoise
  zpExceptionHandler called from unknown
```

**Comment by Mates-K1** [comment]
Sorry, debug log is without page in debug mode.
Which part of debug plugin I should allow?

With debug mode, result is:
![ba998009-1d81-40d9-9dcc-3531d2a4333a](https://user-images.githubusercontent.com/7648991/31780840-2c2bc58e-b4f7-11e7-9e45-890727f6a55f.png)
...no thumbs...

**Comment by sbillard** [comment]
Just use mark release to make it a debug release. No other settings needed. But maybe a better debug will be to add a line before line 1060 of class-images.php:

`if (is_null($this->albumnamealbum)) {
			debugLogBacktrace('null albumnamealbum');
			debuglogVar($this);
		}`

and post the results.

**Comment by Mates-K1** [comment]
Yes, my class-video plugin is disabled. :)

**Comment by sbillard** [comment]
Ok, then the problem is "fixed" in the dev build. What is happening is that search is finding the image records for these mp4 files in the database, so they are "found" images. But since the class-video plugin is not enabled, these image (video) objects cannot be instantiated. Instead a "transient image" is created in their place. The transient image object did not have the albumnamealbum property properly set.

The fix is to properly set the albumnamealbum property. But what you will get displayed will be a bunch of error images. So, you should either refresh your database to remove the mp4 records or you should enable the appropriate media plugins for the files you have recorded in the database.

**Comment by Mates-K1** [comment]
When I refresh database will I be able to search mp4 or flv files by their type/suffix?

**Comment by sbillard** [comment]
If the class-video plugin is not enabled, when you refresh your database all the MP4 entries will be removed. So when you search for them, you will find nothing as they will not be considered "images."

So if you want MP4, etc. files as part of your gallery you must have the class-video plugin enabled.
