### ISSUE TITLE
Setup turns off colorbox plugin

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#674]
I tried my best, but couldn't find what is causing this. Every time I run setup, the colorbox plugin is turned off. This appears to be happening with any theme that uses the colorbox plugin. I do note that it does not appear in the list of check marks shown by the setup program. Also, my setup log is not showing any of the plugin information that it used to show, however, all other plugins are setup as normal.

I should note that I've seen this behavior on the older version I had running as well.

Thanks.

**Comment by sbillard** [comment]
Does the colorbox_js plugin get disabled or is it that the theme options for the colorbox script are reset?

If it is the former, check your php logs for errors. If a plugin faults during setup it will automatically be disabled (so that the fault does not crash the site.) Note: that the plugin details will not be shown unless the site is "marked" debug. There will be a "mark release" button if the "debug" plugin is enabled.

If the latter, check your options for ones that start with 'colorbox_'. There should be only ones like 'colorbox_theme_scripts' which are serialized arrays.

**Comment by sbillard** [comment]
Turns out that the zpBootstrap theme did not play well with others. It was disabling colorbox_js, slideshow, and slideshow2

**Comment by JimBrown** [comment]
All working now. Didn't occur to me to look at what other themes were doing. ;-)

Thanks.

**Comment by sbillard** [comment]
Yes, me neither. I finally put a trap in to catch the reset to see where it was happening.

**Comment by Elinth** [comment]
Hi Stephen, I was looking at the fix for the colorbox issue, it is based on bootstrap. Is there a fix based in the ZPArdoise theme also?

**Comment by sbillard** [comment]
You can search for the same replaced code in your theme. At any rate, 
the distributed zpArdoise does not cause this problem, so compare your 
theme to it if it was based on zpArdoise.


-Stephen
