### ISSUE TITLE
I can't see _GALLERY_INDEX_ token

### ISSUE THREAD

**Issue by vincent3569** [ZenPhoto20/ZenPhoto20#685]
hi

with the latest build, I can't see the _GALLERY_INDEX_ token and rewrite rule as I have seen it with this commit:
https://github.com/ZenPhoto20/ZenPhoto20/commit/6277c232b3c5746ac24b0973379c58d73de10be1

You can see a screenshot
![screenshot010](https://user-images.githubusercontent.com/1224809/33724064-aa0b5cec-db6e-11e7-8525-2bf28308a5d2.png)

**Comment by sbillard** [comment]
Is it possible you do not have the _galleryToken_ plugin enabled? When I have it enabled everything is there as expected. Note also that on the "Rewrite Tokens" page the name is "_GALLERY_PAGE_" not GALLERY_INDEX.

**Comment by vincent3569** [comment]
OK, I haven't seen this plugin.
Btw, why have you created a specific plugin and not included this rewrite rule in rewriteToken plugin ?
It would more simple don't you think?

**Comment by sbillard** [comment]
The plugin has been there for a long while, since before the ZenPhoto20 split. But always an "example" plugin. It is a plugin because not all themes need (or want) this link. I will have to look into how one can "disable" the link--perhaps with an empty value. Then it could be not a plugin.

Generally, most rewrite rules are associated with their respective plugin. E.g. all zenpage links are supplied by the zenpage plugin and the register user by the plugin of the same name.

**Comment by sbillard** [comment]
Ok, I have figured out how to handle this. 8034119844a0e1f7a3cb5981fcfc7047cae62c68
