### ISSUE TITLE
Linux user/group controls on new items

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#696]
Is there an easy way to control permissions and user for the creation of directories etc. before ZP20 is installed?  I'm setting ZP20 up on a new server and while I can change things after installation, I'd prefer not to have to do it every time I upgrade.  Also ability to control user/group for folders created and images uploaded through ZP20 file manager would be helpful (perhaps this already exists and I haven't found it yet).  I put my user into www-data Linux group which is OK but write permissions are all set to owner-only so that's no help.

Thanks

NK

**Comment by sbillard** [comment]
Maybe I am not understanding. If you are talking about Linux permissions on files and folders then there really is only one user--the one which is used to run apache/php scripts.

If you are talking about ZP20 user rights then there is no automated mechanism to set them up. But these have no bearing on Linux file/folder security. You can control who can upload and you can restrict the albums he can upload to with the albums and managed albums rights.

Are you migrating an existing installation? Perhaps the backup/restore utility can be of use. If it is just the users you are moving, you can backup the site with the user list and then on the new site just restore the user table. There may be some issues with passwords when you do this since the password hash seed might be different on the new installation. If so each user would have to reset his password.

I do note on checking on this that there is a bug in that the user can see files in the root of the album folder. Need to fix that.

**Comment by nerdykit** [comment]
Thanks.  I've checked on my problem (and learned a few things).  The owner and group of new folders created from within ZP20 are actually derived from the owner and group for the apache2 server so it's there that I need to make the change, not in ZP20.

NK
