### ISSUE TITLE
utf-8 warning from setup

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#717]
I've just installed 1.5.3.0 on a relatively new server.  The old version of ZP20 was working fine.  The whole arrangement has been moved over to a relatively new server environment but was working fine.  Setup now warns me that "Undefined index UTF-8 in (bunch of directories)  zp-core/setup/index.php on line 813"    Phpmyadmin reports that all tables in this database have utf8_unicode_ci (or utf8mb4_general_ci on another list) which I think is utf8 unicode case insensitive.  (type is InnoDB which is new to me).

Things seem to work OK but I'd like to resolve this anyway for peace of mind.  Any suggestions.  I could export the whole db, create a new db and import back in.  If I do this, what should settings be for the new database?

Thanks

KD

**Comment by sbillard** [comment]
So, what this is telling  us is that the php function "iconv" is reporting it does not support UTF-8 which would be strange. You can get a list of supported character sets. See https://stackoverflow.com/questions/8039232/how-to-get-list-of-supported-encodings-by-iconv-library-in-php

It has nothing to do with the database, It has to do with mismatched filesystem/web character sets such as you would have on a Windows server.

This won't be an issue so long as the filesystem character set is UTF-8. I can suppress the error by changing line 813 to "$charset_defined = @$_zp_UTF8->iconv_sets[FILESYSTEM_CHARSET];" It would be helpful if you would do that and see what transpires.

You would not get this error if the PHP "iconv" function does not exist. Then the translations use "mb_convert_encoding" (if present.) I am guessing that your other installations either did not have "iconv" or whatever is making it not support UTF-8 is correct on them.

**Comment by nerdykit** [comment]
Modifying line 813 as you suggest suppresses or removes the need for the error warning; I'm not sure which, but when I run setup again, I no longer get this warning.  I'm not sure if I need to fix anything or just leave matters as they are.  What do you recommend?  The server itself is running raspbian (debian variant) (fwiw ZP20 runs well off a raspberry pi).  Did the iconv -l per the link on supported encodings and got a long list which includes UTF-8.

**Comment by sbillard** [comment]
I don't think you need to fix anything. Your file system will be UTF-8 which is the same as your URLs so no character set translation is done. Strange that the system reports iconv supports UTF-8 but the ZP test fails. But since this is the first I have heard of this error and I have some code changes that will "fix" it so long as the system also has the mb_convert_encoding function I think we should just ignore the failure.

If you want to try the changes, they are in my development build: https://github.com/sbillard/ZenPhoto20-DEV/

They will be in the next support update, but I don't consider it a priority.

**Comment by nerdykit** [comment]
Thanks.  Will close this for now.
