### ISSUE TITLE
sitemap-extended not working

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#737]
Version 1.5.3.12. Please see debug log attached.

Enabled the sitemap-extended plugin. After trying to generate a sitemap, the sitemap-extended plugin is disabled.

Let me know if you need anything else.

Thanks.

[debug.log](https://github.com/ZenPhoto20/ZenPhoto20/files/1771688/debug.log)

**Comment by sbillard** [comment]
This is really strange. The log claims that the function _sitemap::passAlbums()_ is undefined. Yet it is a static function of the sitemap class and this call is coming from another static function within the class!

The reason the plugin is disabled (and the rest of the error messages) is because if we get a non-recoverable fault within a plugin the ZenPhoto20 cleanup code will disable the plugin to avoid a permanent crash of the site.

So the question is how did this error occur. Maybe there is another error reported in your server error logs? Nothing in the debug log would indicate any other errors. Also I can run sitemap and do not get the failure. Is this repeatable?

**Comment by sbillard** [comment]
[sitemap-extended.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1772390/sitemap-extended.zip)

Well, I did discover some poor coding in the plugin. (use of the class name 'sitemap' rather than 'self' within the class. Not good coding (but then the author was a rank amature.) Not sure why you got the failure still, but maybe the attached version will work for you

**Comment by JimBrown** [comment]
Attached version is now working. Thanks once again!

**Comment by sbillard** [comment]
Good that it works, but I really do not understand why it failed. The bad code has been there since before the ZenPnoto20 branch was created--in other words, years. Anything on your site changed recently? Not really a big deal, but I am curious.

**Comment by JimBrown** [comment]
No recent changes that I am aware of, both on my local WAMP, and my host. Host is using Apache 2.2.24, PHP 5.4.33, and MySQL 5.5.58-cll.

**Comment by sbillard** [comment]
fix is in 1.5.3.15
