### ISSUE TITLE
Minor upgrade issue re versions

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#739]
Whenever I upgrade I get warnings that my php version may be to low when in reality it's over the requirement (at 7.0.27),  same sort of thing for MySQLi version, my version is higher than minimum requirement.  Not a problem but potentially concerning for new users when it really needn't be.

NK

**Comment by sbillard** [comment]
[index.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1772351/index.zip)

See if this setup index.php makes any difference.

**Comment by nerdykit** [comment]
Sorry, just found this.  Have tried the replacement index.php file for setup and setup continues to warn about minimum versions of php and mysql when my versions are higher than the requirement.  Maybe this "non-issue" could be better resolved with change of wording of the warnings to make it clear that if the available version of php etc. is greater than the minimum required then this warning can be safely disregarded.  My concern was only for the inexperienced person installing who might become needlessly worried about their installation of ZP20.

![screenshot 2018-03-03 at 1 00 44 pm](https://user-images.githubusercontent.com/3220548/36939657-761d7bcc-1ee9-11e8-97d7-c6135caafa71.jpg)

**Comment by sbillard** [comment]
The warning comes because the software version is below what ZenPhoto20 desires. If it were below the required version the message would be an error.

I am not sure what would be better wording. According to http://php.net/supported-versions.php version 7 is out of general support and will be out of security support by the end of this year. That would seem to be something that a person might legitimately be worried about.

It is less clear with MySQL since I cannot find an equivalent support chart, but the warning is still relevant as there are features that are not available on the earlier versions, utf8mb4 support, for example.

But I am open to suggestions on how to make these warnings compelling but not frightening.

**Comment by nerdykit** [comment]
Thanks for thinking about this.  It's really a non-issue and I'm going to close for now.  If I have a suggestion, I'll submit it.
