### ISSUE TITLE
Translate tags

### ISSUE THREAD

**Issue by You85** [ZenPhoto20/ZenPhoto20#742]
I use zenphoto and I am impressed by the features it offers such as the translation of the titles of descriptions or tags. Nevertheless, I want to know if it is possible to translate everything automatically. I explain my zenphoto is in English and I want to translate it to other languages.
So, there is a pligin that automatically translates tags (148 tags)

**Comment by sbillard** [comment]
ZenPhoto20 is not in the translation business. We use PoEdit to translate the system messages. (This is done either by volunteer translators or by the PoEdit WEB based machine translations.) Any theme specific texts such as titles or (in your case) tags must be somehow translated and inserted. ZenPhoto20 has the concept of language specific tags, so if a translation is available it can be assigned to appear only for a viewer using that language. For instance you can create tags on the Tag admin page and assign them to a specific language. 

I suppose it would be possible to capture the tags and use PoEdit to translate them then insert the translations. But the real issue is the translation in the first place. If this approach is taken you would create a PoEdit .po file with your tags and use PoEdit to provide the translations. A plugin could then use this .po file and the .mo file that PoEdit creates to insert the tag translations.

If this is something you would be interested in trying I would be interested in working with you. I think it would be a useful addition to ZenPhoto20. Please checl out PoEdit and see if it works for you. If so attach a .po file with your tags to this ticket and I will work on the plugin to process the tags.

A similar thing could be done with the theme content such as titles, etc. However that would be much more complicated as there needs to be some mechanism to associate a particular string with the object/text field where it belongs.

**Comment by You85** [comment]
Hello @sbillard and thank you for your answer. I'm new to programming but can I do that with Google Cloud Translation API without using Poedit.
https://cloud.google.com/translate/docs/

Thank you

**Comment by sbillard** [comment]
This looks very promising.

A plugin could list all the tags that are not language specific and you could choose which to translate. They would be translated into the ZP20 enabled languages (provided that the cloud service has that language.)

Similarly, other database fields could be searched for cases where there is only one language string and these could be offered for translations.

Are you interested in contributing to the development of this? We could create a GitHub project for it.

**Comment by You85** [comment]
wahoo you are brilliant. Thank you for that answer.

I am not a developer but I can contribute by translating. moreover this can be an extremely powerful feature that can save users a lot of time.

**Comment by sbillard** [comment]
No problem. At least you can help test this. Also make suggestions as to how you would like to see it work. It may take a little time to come up with the code. I have to familiarize myself with the Google tool and figure our how things will work (this is where your ideas will be helpful, you are the targeted user, after all.)

**Comment by You85** [comment]
The plugin can list all the tags to translate. he can either translate everything or check the tags he wants to translate.

**Comment by sbillard** [comment]
Upon investigation I have found that the Google Cloud translation service is a for-fee service. This severely limits its applicability to the ZenPhoto20 user base and not incidentally would cost more than my time to implement.

You could post on the ZenPhoto20 Google group and see if there is any interest and perhaps create a funding project to move this idea forward.

But the idea was not without its benefits. I have made some improvements on how language based tags are handled on the TAGS page. Tags with translations are now organized so that the translations immediately follow the "master" tag. With these changes you could manually use https://translate.google.com/ to translate tags then paste them into ZenPhoto20.

You can preview these changes with this development build: 
[setup-1.5.3.17.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1786155/setup-1.5.3.17.zip)

**Comment by sbillard** [comment]
Since there has been no action on this it will be closed.

Should there be further interest, perhaps a free translation service with PHP support, a new ticket can be opened.
