### ISSUE TITLE
cache images for thumbnails are created twice

### ISSUE THREAD

**Issue by vincent3569** [ZenPhoto20/ZenPhoto20#764]
Hi

as far I can see, cache_manager have issue with thumbnails.
cache_manager creates one cache image size and `printImageThumb()` creates other cache image size. so cache image for thumbnails are created twice, so the cache_manager images from cache_manager are useless.

I have a look on cache folder and there is some examples:
-cache images from theme (when I discorer album with my browser, with theme basic)
img_8965_w220_h220_cw734_ch734_cx305_cy0_thumb.jpg
img_8991_220_w220_h220_thumb.jpg

-cache images from cache manager
img_8965_220_cw734_ch734_cx305_cy0_thumb.jpg
img_8991_220_cw220_ch220_thumb.jpg

I think first cache file names are correct with theme, but is wrong with cache manager.

**Comment by sbillard** [comment]
What theme is this with?

**Comment by sbillard** [comment]
I am not seeing this. In particular, none of the cache sizes include the cx and cy values.

My theme based cache images all are like: eia1956-small_100_cw100_ch100_thumb.jpg And, the default thumb size for Basic is 100. What are the theme options you have for Basic?

**Comment by sbillard** [comment]
There are some changes in the 1.6.0.1 update that might impact this. Please try that build.

**Comment by vincent3569** [comment]
I have a look, and it seems to be fine now except one case.

For some thumbs, I defined custom thumbnail cropping.
In theme options, if I set `Crop thumbnails`,  cache images are good (custom cropped thumb)
But if I disable `Crop thumbnails`, cache images are not good : cache_manager generates custom cropped thumb cache images and not generates uncropped thumb.

example (with `Crop thumbnails` disabled and `thumb size` 150)
img_8986_150_thumb.jpg 
img_8987_150_cw600_ch600_cx0_cy299_thumb.jpg

when I visit my album, the right thumb cache image is generated
img_8987_150_thumb.jpg

**Comment by vincent3569** [comment]
of course, it is logical that cache_manager doesn't manage custom cropping values by default as it is specfic to each image.

but, by the way, cache_manager generates custom cropped thumb cache images, like img_8987_150_cw600_ch600_cx0_cy299_thumb.jpg. well !!

but it does it, even if `Crop thumbnails` is disabled for the theme. not good !
in that case, cache manager should only generate a sized thumb as img_8987_150_thumb.jpg.

**Comment by sbillard** [comment]
For me, when thumb crop is not set the custom thumb cropping is not generated. This may be due to some recent changes post 1.6.0, I do not know for sure and it makes no sense to spend time figuring out when the fix happened.

You can try the master build or my development build. (I am testing these things on the development build.)  The one thing that I did find is that there was an "issue" with the custom cropped image caching parameters. It would use w=x and h=y when x was equal to y. In that case it should have used size=x and had w and h empty. This was the one difference I did find in caching from cacheManager and from normal image loading. That is also fixed.
