### ISSUE TITLE
Feature request - Comments notifications

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#773]
Feature request- Just a quick question about this awesome CMS. If one user commented on a specific album or picture, an email is send to the admin. If a second user comments also on the same album or picture. is it possible for both of them get a notification email after the second user commented as kind of like a discussion tool? This without displaying the email addresses of the users but in the email showing only that the user with user name x has commented on the same picture. Similar to what Facebook does? Now only the admin gets the comments email I think.

**Comment by sbillard** [comment]
This is again the realm of RSS feeds. If the user is interested in comments on a particular picture he should subscribe to the RSS feed for that picture.

**Comment by Elinth** [comment]
Ah, I see. My users have no clue what RSS is. I think for comments RSS is not ideal anyway. For news it is. Just from a usability point of view: When I am a user I would never think of subscribing to RSS just for the comments of a picture..

**Comment by sbillard** [comment]
Well, then the answer is educate them.

Some things to remember:
Comments are posted on a specific item from your site, e.g. an image. There is no concept of posting a comment upon a comment. While a human may be able to discern from the comment that it is about another posting all the site knows is that someone has posted a comment on the item.

Anyway, what you want is exactly what RSS was designed to do. It might be possible to add a prompt after a user comments asking if he wants to subscribe to RSS for the item. It would not be possible to know if he is already subscribed, though, so the prompt would come with each comment posting.

It would also be possible to create a plugin that did something similar to what you ask. But since there is no way of knowing a comment is directed at a specific user, all users who commented would necessarily get the e-mail. Since this is really what RSS does, I would only consider this implementation as a special custom plugin which would have to be commissioned.

**Comment by Elinth** [comment]
Ok.. Thank you.
