### ISSUE TITLE
Bulk Actions not working on image list page

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#791]
As noted in my reply to issue re: images not published.

I've played with this further and found that there is no problem with the Filter drop down menu but I cannot get Bulk Actions to work from the images 'list' page.  I CAN get Bulk Actions to work from the Image Order page, just not from the main image list page.

NK

**Comment by sbillard** [comment]
This is supposed to work, the code is there, but obviously it is not working. Hopefully I can find the cause.

**Comment by sbillard** [comment]
So, here is the issue:

The bulk actions get processed correctly, but then the normal "save" action happens which reverses some of the actions such as publish state.

I think that switching the order of processing would "fix" this. Bulk actions would then override any individual action. 

Does this make sense to you?

**Comment by nerdykit** [comment]
Sorry what you've written above isn't clear for me.  What I'm finding is that on the page admin-edit.php?page=edit&album=travel%2Fspain-portugal-2018%2Fbilbao&tab=imageinfo or any similar page, (set to show 5 of the images in that directory) if I set the Bulk Actions menu to Set to Unpublished, and check the "Select All" box and then click Apply having done no other action on that page.... nothing happens.  No images have their published status changed.  On the other hand, if I'm working on the Image order page with all its thumbnails and do exactly the same operation except of course all of the images are present, not just five.  Then the published status IS changed.  It still seems to me that Bulk Actions on the edit album images page isn't working.  Maybe I'm missing what is necessary to trigger the bulk action that has been requested from the menu.  I've assumed that it was necessary to "Apply" the Bulk Action (even though the Apply button does not turn green).  I've tried moving to the next page of images instead of clicking Apply.  What triggers the Bulk Action after I've specified it?

**Comment by sbillard** [comment]
You are correct that the end result is that nothing has changed, but there were actually things going on.

FIrst the bulk actions got applied setting the checked images to published. Then the image was "saved." Since the state of the image when you pressed apply was not published, that state got stored. Certainly not the expected outcome, I agree.

Anyway, with the fix, if you set bulk actions and press apply, only the bulk actions will be applied. I think that is what most people will expect, but it is certainly possible for you to update an image description then select bulk actions. Then the image description update will be lost.
