### ISSUE TITLE
Changing language when running setup

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#806]
I have English as primary language in gallery.
I run setup and change language from English to Czech.
Site changes to Czech.
After clicking GO! ("Jdeme na to!" in Czech) next site is in English again (installing themes, plugins...).

I would expect the entire installation will continue in Czech.... Or may be this option change my primary language in gallery to Czech.

**Comment by sbillard** [comment]
Hmm. This seems to work for me. I used German because I understand it better than Czech. The only issues I had were that some phrases were not translated. But the general language of the site stayed in German until I reset it to English on the options page.

Do you have the dynamic-locale plugin enabled? Do you have gallery sessions enabled?

**Comment by Mates-K1** [comment]
In general I have enabled four languages in gallery - English (US), Czech, Slovak and HTTP Accept Language. So when I run setup I can choose between three languages. So I do it.

I have disable both.

**Comment by sbillard** [comment]
How are you selecting the language in setup? Again, dynamic-locale? gallery sessions?

Unless I can reproduce this I do not see how I can fix it. For me it works. (I have lots of languages enabled.)

**Comment by Mates-K1** [comment]
I select languages by flags in right-bottom corner:
![80c41e85-513b-4536-ba4b-50cf1244485b](https://user-images.githubusercontent.com/7648991/42588673-d151429c-853e-11e8-9c48-61874ae0e45f.png)

I apologize for misunderstanding, by "I have disable both" I thought that dynamic-locale plugin is disabled and gallery sessions are not enabled too..

**Comment by sbillard** [comment]
OK, thanks. I just wanted to setup my test to match your configuration. I have done so and things still work. Can you check your browser and see if there is a cookie named "dynamic_locale"? If so what is its content. The flag language switch is controlled by cookies.

Also, is your site connection http or https? Does that change when the second page of setup comes up?

Are there any other circumstances where the language gets lost like this?

**Comment by Mates-K1** [comment]
There is no that cookie before running setup (I delete it before run setup) and after running first page. After I change language, setup create cookie named "dynamic_locale", it contains "en_US".

I use https. On second page, there is still https and in cookie there is still "en_US". 

Tested on my PC and mobile too.

I do not know about any other circumstances.

**Comment by sbillard** [comment]
Just so I understand correctly:

You run setup (and it is in English.) You click the Czech flag and the language switches to Czech. You look at the dynamic_locale cookie at this point and it shows "en_US"?

Is there only one dynamic_locale cookie? In the cookie details, is the domain and path correct? Is the creation date consistent with when you checked the flag? What is the setting of "send for"?

We can further investigate by setting a debug option. In the plugin options of development/debug there is a setting for "Log language selection process". Enable the plugin, set that option, and click the "Maark release" button so that the ZenPhoto20 version shows it is a debug release and the locale debug is set.

Go to the first page of Setup. Manually delete the debug log. (Use FTP or something. Do not delete it from ZenPhoto20!) click the Czech flag, then the "GO" button. When the second page starts, Cancel the browser loading. Then rename or download the debug log manually. so that its content is preserved. Attach the log you retrieved to this ticket. 

You can then reset the debug option, mark the release "released", and delete the newly debug log.

**Comment by Mates-K1** [comment]
It's a bit different.
I run setup (it is in Czech). Click English flag and language switch to English, then i look at dynamic_locale cookie and at this point and it shows "en_US".

Yes, there is only one dynamic_locale cookie.
....

**Comment by Mates-K1** [comment]
![nepojmenovany 1](https://user-images.githubusercontent.com/7648991/42728191-f7e5c23e-87b4-11e8-805d-e4c960df496e.jpg)
[debug.log](https://github.com/ZenPhoto20/ZenPhoto20/files/2195254/debug.log)

**Comment by Mates-K1** [comment]
Amateur and fast video:
https://data.martinkroul.cz/subdom/data/index.php/s/PHW5pwKHMk92sRr

**Comment by sbillard** [comment]
Ok, now I can reproduce this. Thanks for the additional details.

**Comment by sbillard** [comment]
Ok, the problem is that the user's language specification took precedence over the cookie.

I propose the following priority for selecting the language:

1. any url setting (e.g. lalnguage=en_us, or en.website.com)
2. any language cookie
3. the user selected language (from admin/user)
4. the site specified language
5. the browser specified HTTP_ACCEPT_LANGUAGE language(s)
6. the site language defined by the dynamic_locale plugin
7. English (if enabled)
8. The first enabled language from the general options language list

The difference from the existing priority is that the language cookie moves up in front of the user's selected language.

**Comment by Mates-K1** [comment]
Yes, it works. Thanks as ever. 🥇

**Comment by Mates-K1** [comment]
Just... After returning to back-end of gallery, language is back to user main language. I think this solution is right (I select language for setup, not for back-end etc.) 👍
